package viewFuncionario;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Ficha;
import model.dao.FichaDAO;

public class FichaCatalografica extends javax.swing.JInternalFrame {

    public FichaCatalografica() {
        initComponents();
        
        DefaultTableModel modelo = (DefaultTableModel) tabelaFicha.getModel(); // FAZER ORDENAÇÃO NA TABELA
        tabelaFicha.setRowSorter(new TableRowSorter(modelo));
        readTabela();
    }
    
    public void cleanFields(){
        txtNome.setText("");
        txtTitulo.setText("");
        txtAno.setText("");
        txtCurso.setText("");
        txtTrabalho.setText("");
        txtStatus.setText("");
    }
    public void readTabela(){
        DefaultTableModel modelo = (DefaultTableModel) tabelaFicha.getModel();
        modelo.setNumRows(0);
        FichaDAO fdao = new FichaDAO();
        
        for(Ficha f: fdao.read()){
            
            modelo.addRow(new Object[]{
                f.getId(),
                f.getNome(),
                f.getTitulo(),
                f.getAno(),
                f.getCurso(),
                f.getTipoTrabalho(),
                f.getStatus()
        });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtAno = new javax.swing.JTextField();
        btnGerar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaFicha = new javax.swing.JTable();
        txtTrabalho = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCurso = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Livros"));
        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("NOME");

        jLabel2.setText("TITULO");

        jLabel3.setText("ANO");

        btnGerar.setText("Gerar");
        btnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarActionPerformed(evt);
            }
        });

        tabelaFicha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "TITULO", "ANO", "CURSO", "TIPO DE TRABLHO", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaFicha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaFichaMouseClicked(evt);
            }
        });
        tabelaFicha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaFichaKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tabelaFicha);

        jLabel4.setText("TIPO DE TRABALHO");

        jLabel5.setText("CURSO");

        jLabel6.setText("STATUS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnGerar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNome))
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtCurso, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(txtAno, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                            .addComponent(txtStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))))
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(jLabel1)
                    .addContainerGap(832, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addContainerGap(621, Short.MAX_VALUE)))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 915, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed
        Ficha fi = new Ficha();
        FichaDAO dao = new FichaDAO();
        if (tabelaFicha.getSelectedRow()!= -1){
            fi.setNome(txtNome.getText());
            fi.setTitulo(txtTitulo.getText());
            fi.setAno(Integer.parseInt(txtAno.getText()));
            fi.setCurso(txtCurso.getText());
            fi.setTipoTrabalho(txtTrabalho.getText());
            fi.setStatus(Integer.parseInt(txtStatus.getText()));
            fi.setId((int)tabelaFicha.getValueAt(tabelaFicha.getSelectedRow(), 0));
            dao.update(fi);
            cleanFields();
            readTabela();
        }else{
            JOptionPane.showMessageDialog(null, "Selecionar Ficha para Gerar");
        }
    }//GEN-LAST:event_btnGerarActionPerformed
    private void tabelaFichaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaFichaMouseClicked
        if (tabelaFicha.getSelectedRow() != -1){
            txtNome.setText(tabelaFicha.getValueAt(tabelaFicha.getSelectedRow(), 1).toString());
            txtTitulo.setText(tabelaFicha.getValueAt(tabelaFicha.getSelectedRow(), 2).toString());
            txtAno.setText(tabelaFicha.getValueAt(tabelaFicha.getSelectedRow(), 3).toString());
            txtCurso.setText(tabelaFicha.getValueAt(tabelaFicha.getSelectedRow(), 4).toString());
            txtTrabalho.setText(tabelaFicha.getValueAt(tabelaFicha.getSelectedRow(), 5).toString());
            txtStatus.setText(tabelaFicha.getValueAt(tabelaFicha.getSelectedRow(), 6).toString());
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma Ficha para Excluir ");
        }
    }//GEN-LAST:event_tabelaFichaMouseClicked
    private void tabelaFichaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaFichaKeyReleased
         if (tabelaFicha.getSelectedRow() != -1){                                        //EDITAR ITENS DA TABELA
            txtNome.setText(tabelaFicha.getValueAt(tabelaFicha.getSelectedRow(), 1).toString());
            txtTitulo.setText(tabelaFicha.getValueAt(tabelaFicha.getSelectedRow(), 2).toString());
            txtAno.setText(tabelaFicha.getValueAt(tabelaFicha.getSelectedRow(), 3).toString());
            txtCurso.setText(tabelaFicha.getValueAt(tabelaFicha.getSelectedRow(), 4).toString());
            txtTrabalho.setText(tabelaFicha.getValueAt(tabelaFicha.getSelectedRow(), 5).toString());
            txtStatus.setText(tabelaFicha.getValueAt(tabelaFicha.getSelectedRow(), 6).toString());
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma Ficha para Editar ");
        }
    }//GEN-LAST:event_tabelaFichaKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabelaFicha;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtCurso;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtTrabalho;
    // End of variables declaration//GEN-END:variables
}
