package viewFuncionario;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Pessoa;
import model.dao.PessoaDAO;

public class IncluirAcervo extends javax.swing.JInternalFrame {

    public IncluirAcervo() {
        initComponents();
        
        DefaultTableModel modelo = (DefaultTableModel) tabelaAcervo.getModel(); // FAZER ORDENAÇÃO NA TABELA
        tabelaAcervo.setRowSorter(new TableRowSorter(modelo));
        readTabela();
    }
    
    public void readTabela(){
        DefaultTableModel modelo = (DefaultTableModel) tabelaAcervo.getModel();
        modelo.setNumRows(0);
        PessoaDAO pdao = new PessoaDAO();
        
        for (Pessoa p: pdao.read()){
            
            modelo.addRow(new Object[]{
                p.getMatricula(),
                p.getPsw(),
                p.getFuncao()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaAcervo = new javax.swing.JTable();
        jPanelInsertAcervo = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JTextField();
        txtEditora = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEstante = new javax.swing.JTextField();
        txtPrateleira = new javax.swing.JTextField();
        txtAno = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanelPesquisa = new javax.swing.JPanel();
        btnExcluir = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        txtTitulo1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnExcluir1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Livros"));
        setClosable(true);
        setMaximizable(true);
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setWheelScrollingEnabled(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(700, 550));
        jPanel1.setMinimumSize(new java.awt.Dimension(700, 550));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 550));
        jPanel1.setRequestFocusEnabled(false);

        tabelaAcervo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TITULO", "EDITORA", "ANO", "STATUS", "ESTANTE", "PRATELEITA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaAcervo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabelaAcervo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaAcervoMouseClicked(evt);
            }
        });
        tabelaAcervo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaAcervoKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tabelaAcervo);

        txtTitulo.setMaximumSize(new java.awt.Dimension(30, 100));
        txtTitulo.setMinimumSize(new java.awt.Dimension(30, 100));
        txtTitulo.setPreferredSize(new java.awt.Dimension(30, 100));

        txtEditora.setMaximumSize(new java.awt.Dimension(30, 100));
        txtEditora.setMinimumSize(new java.awt.Dimension(30, 100));
        txtEditora.setPreferredSize(new java.awt.Dimension(30, 100));

        jLabel1.setText("Titulo");

        jLabel2.setText("Editora");

        jLabel4.setText("Estante");

        txtEstante.setMaximumSize(new java.awt.Dimension(30, 100));
        txtEstante.setMinimumSize(new java.awt.Dimension(30, 100));
        txtEstante.setPreferredSize(new java.awt.Dimension(30, 100));

        txtPrateleira.setMaximumSize(new java.awt.Dimension(30, 100));
        txtPrateleira.setMinimumSize(new java.awt.Dimension(30, 100));
        txtPrateleira.setPreferredSize(new java.awt.Dimension(30, 100));

        txtAno.setMaximumSize(new java.awt.Dimension(30, 100));
        txtAno.setMinimumSize(new java.awt.Dimension(30, 100));
        txtAno.setPreferredSize(new java.awt.Dimension(30, 100));

        txtStatus.setMaximumSize(new java.awt.Dimension(30, 100));
        txtStatus.setMinimumSize(new java.awt.Dimension(30, 100));
        txtStatus.setPreferredSize(new java.awt.Dimension(30, 100));

        jLabel5.setText("Prateleira");

        jLabel6.setText("Ano");

        jLabel7.setText("Status");

        javax.swing.GroupLayout jPanelInsertAcervoLayout = new javax.swing.GroupLayout(jPanelInsertAcervo);
        jPanelInsertAcervo.setLayout(jPanelInsertAcervoLayout);
        jPanelInsertAcervoLayout.setHorizontalGroup(
            jPanelInsertAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInsertAcervoLayout.createSequentialGroup()
                .addGroup(jPanelInsertAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanelInsertAcervoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelInsertAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelInsertAcervoLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanelInsertAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEstante, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelInsertAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtPrateleira, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanelInsertAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInsertAcervoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(266, 266, 266))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInsertAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelInsertAcervoLayout.createSequentialGroup()
                            .addComponent(txtEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInsertAcervoLayout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(jPanelInsertAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addGap(45, 45, 45)
                            .addGroup(jPanelInsertAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))
                            .addGap(47, 47, 47)))))
        );
        jPanelInsertAcervoLayout.setVerticalGroup(
            jPanelInsertAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInsertAcervoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInsertAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInsertAcervoLayout.createSequentialGroup()
                        .addGroup(jPanelInsertAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelInsertAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelInsertAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)))
                    .addGroup(jPanelInsertAcervoLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelInsertAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEstante, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrateleira, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnExcluir.setText("Excluir");
        btnExcluir.setMaximumSize(new java.awt.Dimension(140, 25));
        btnExcluir.setMinimumSize(new java.awt.Dimension(140, 25));
        btnExcluir.setPreferredSize(new java.awt.Dimension(140, 25));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar");
        btnAtualizar.setMaximumSize(new java.awt.Dimension(140, 25));
        btnAtualizar.setMinimumSize(new java.awt.Dimension(140, 25));
        btnAtualizar.setPreferredSize(new java.awt.Dimension(140, 25));
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setMaximumSize(new java.awt.Dimension(140, 25));
        btnCadastrar.setMinimumSize(new java.awt.Dimension(140, 25));
        btnCadastrar.setPreferredSize(new java.awt.Dimension(140, 25));
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        txtTitulo1.setMaximumSize(new java.awt.Dimension(30, 100));
        txtTitulo1.setMinimumSize(new java.awt.Dimension(30, 100));
        txtTitulo1.setPreferredSize(new java.awt.Dimension(550, 700));

        jLabel8.setText("Campo de Pesquisa");

        btnExcluir1.setText("Pesquisar");
        btnExcluir1.setMaximumSize(new java.awt.Dimension(140, 25));
        btnExcluir1.setMinimumSize(new java.awt.Dimension(140, 25));
        btnExcluir1.setPreferredSize(new java.awt.Dimension(140, 25));
        btnExcluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPesquisaLayout = new javax.swing.GroupLayout(jPanelPesquisa);
        jPanelPesquisa.setLayout(jPanelPesquisaLayout);
        jPanelPesquisaLayout.setHorizontalGroup(
            jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesquisaLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(jPanelPesquisaLayout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelPesquisaLayout.setVerticalGroup(
            jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel3.setText("Menu Acervo");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(276, 276, 276))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelInsertAcervo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelInsertAcervo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jPanel1);
        jPanel1.getAccessibleContext().setAccessibleName("");
        jPanel1.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed

        DefaultTableModel dtmLivros = (DefaultTableModel)tabelaAcervo.getModel();         //ADICIONAR ITENS NA TABELA
        Object[] dados = {txtTitulo.getText(), txtEditora.getText(), txtEditora.getText()};
        dtmLivros.addRow(dados);
        readTabela();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        //        System.out.println("Linha Selecionada"+tabelaLivros.getSelectedRow());    REMOVER LINHA SELECIONADA NA TABELA

        if (tabelaAcervo.getSelectedRow() != -1){
        DefaultTableModel dtmLivros = (DefaultTableModel)tabelaAcervo.getModel();
        dtmLivros.removeRow(tabelaAcervo.getSelectedRow());
        }else{
            JOptionPane.showMessageDialog(null, "Selecione Um Livro para Excluir ");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        
        if (tabelaAcervo.getSelectedRow() != -1){
           tabelaAcervo.setValueAt(txtTitulo.getText(), tabelaAcervo.getSelectedRow(), 0);
           tabelaAcervo.setValueAt(txtEditora.getText(), tabelaAcervo.getSelectedRow(), 1);
           tabelaAcervo.setValueAt(txtEditora.getText(), tabelaAcervo.getSelectedRow(), 2);
        }else{
            JOptionPane.showMessageDialog(null, "Selecione Um Livro para Editar ");
            
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void tabelaAcervoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaAcervoKeyReleased
        if (tabelaAcervo.getSelectedRow() != -1){                                        //EDITAR ITENS DA TABELA
            txtTitulo.setText(tabelaAcervo.getValueAt(tabelaAcervo.getSelectedRow(), 0).toString());
            txtEditora.setText(tabelaAcervo.getValueAt(tabelaAcervo.getSelectedRow(), 1).toString());
            txtEditora.setText(tabelaAcervo.getValueAt(tabelaAcervo.getSelectedRow(), 2).toString());
        }else{
            JOptionPane.showMessageDialog(null, "Selecione Um Livro para Editar ");
        }

    }//GEN-LAST:event_tabelaAcervoKeyReleased

    private void tabelaAcervoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaAcervoMouseClicked

        if (tabelaAcervo.getSelectedRow() != -1){
            txtTitulo.setText(tabelaAcervo.getValueAt(tabelaAcervo.getSelectedRow(), 0).toString());
            txtEditora.setText(tabelaAcervo.getValueAt(tabelaAcervo.getSelectedRow(), 1).toString());
            txtEditora.setText(tabelaAcervo.getValueAt(tabelaAcervo.getSelectedRow(), 2).toString());
        }else{
            JOptionPane.showMessageDialog(null, "Selecione Um Livro para Excluir ");
        }
    }//GEN-LAST:event_tabelaAcervoMouseClicked

    private void btnExcluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluir1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluir1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnExcluir1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelInsertAcervo;
    private javax.swing.JPanel jPanelPesquisa;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabelaAcervo;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtEditora;
    private javax.swing.JTextField txtEstante;
    private javax.swing.JTextField txtPrateleira;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtTitulo1;
    // End of variables declaration//GEN-END:variables
}
