package viewFuncionario;

import database.DataBase;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Acervo;
import model.dao.AcervoDAO;

public class IncluirAcervo extends javax.swing.JInternalFrame {

    public IncluirAcervo() {
        initComponents();
        
        DefaultTableModel modelo = (DefaultTableModel) tabelaAcervo.getModel(); // FAZER ORDENAÇÃO NA TABELA
        tabelaAcervo.setRowSorter(new TableRowSorter(modelo));
        //readTabela();
    }
    
    public void cleanFields(){
        txtTitulo.setText("");
        txtEditora.setText("");
        txtAno.setText("");
        txtStatus.setText("");
        txtEstante.setText("");
        txtPrateleira.setText("");
    }
    
    
    public void readTabela(){
        DefaultTableModel modelo = (DefaultTableModel) tabelaAcervo.getModel();
        modelo.setNumRows(0);
        AcervoDAO adao = new AcervoDAO();
        
        for (Acervo a: adao.read()){
            
            modelo.addRow(new Object[]{
                a.getId(),
                a.getTitulo(),
                a.getEditora(),
                a.getAno(),
                a.getEstante(),
                a.getPrateleira(),
                a.getStatus()
                
            });
        }
    }
    
    public void readTab(){
        DefaultTableModel modelo = (DefaultTableModel) tabelaAcervo.getModel();
        modelo.setNumRows(0);
        AcervoDAO adao = new AcervoDAO();
        
        for (Acervo a: AcervoDAO.selectAcervo(txtBusca.getText())){
            
            modelo.addRow(new Object[]{
                a.getId(),
                a.getTitulo(),
                a.getEditora(),
                a.getAno(),
                a.getEstante(),
                a.getPrateleira(),
                a.getStatus()
                
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaAcervo = new javax.swing.JTable();
        jPanelInsertAcervo = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JTextField();
        txtEditora = new javax.swing.JTextField();
        txtEstante = new javax.swing.JTextField();
        txtPrateleira = new javax.swing.JTextField();
        txtAno = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanelPesquisa = new javax.swing.JPanel();
        btnExcluir = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnListAllBooks = new javax.swing.JButton();
        txtBusca = new javax.swing.JTextField();
        btnBusca = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Livros"));
        setClosable(true);
        setTitle("Menu Acervo");
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setWheelScrollingEnabled(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(700, 550));
        jPanel1.setMinimumSize(new java.awt.Dimension(700, 550));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 550));
        jPanel1.setRequestFocusEnabled(false);

        tabelaAcervo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TITULO", "EDITORA", "ANO", "ESTANTE", "PRATELEITA", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaAcervo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabelaAcervo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaAcervoMouseClicked(evt);
            }
        });
        tabelaAcervo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaAcervoKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tabelaAcervo);

        txtTitulo.setMaximumSize(new java.awt.Dimension(30, 100));
        txtTitulo.setMinimumSize(new java.awt.Dimension(30, 100));
        txtTitulo.setPreferredSize(new java.awt.Dimension(30, 100));

        txtEditora.setMaximumSize(new java.awt.Dimension(30, 100));
        txtEditora.setMinimumSize(new java.awt.Dimension(30, 100));
        txtEditora.setPreferredSize(new java.awt.Dimension(30, 100));

        txtEstante.setMaximumSize(new java.awt.Dimension(30, 100));
        txtEstante.setMinimumSize(new java.awt.Dimension(30, 100));
        txtEstante.setPreferredSize(new java.awt.Dimension(30, 100));

        txtPrateleira.setMaximumSize(new java.awt.Dimension(30, 100));
        txtPrateleira.setMinimumSize(new java.awt.Dimension(30, 100));
        txtPrateleira.setPreferredSize(new java.awt.Dimension(30, 100));

        txtAno.setMaximumSize(new java.awt.Dimension(30, 100));
        txtAno.setMinimumSize(new java.awt.Dimension(30, 100));
        txtAno.setPreferredSize(new java.awt.Dimension(30, 100));

        txtStatus.setMaximumSize(new java.awt.Dimension(30, 100));
        txtStatus.setMinimumSize(new java.awt.Dimension(30, 100));
        txtStatus.setPreferredSize(new java.awt.Dimension(30, 100));

        jLabel1.setText("Titulo");

        jLabel2.setText("Editora");

        jLabel4.setText("Estante");

        jLabel5.setText("Prateleira");

        jLabel6.setText("Ano");

        jLabel7.setText("Status");

        javax.swing.GroupLayout jPanelInsertAcervoLayout = new javax.swing.GroupLayout(jPanelInsertAcervo);
        jPanelInsertAcervo.setLayout(jPanelInsertAcervoLayout);
        jPanelInsertAcervoLayout.setHorizontalGroup(
            jPanelInsertAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInsertAcervoLayout.createSequentialGroup()
                .addGroup(jPanelInsertAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInsertAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanelInsertAcervoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelInsertAcervoLayout.createSequentialGroup()
                            .addGap(48, 48, 48)
                            .addGroup(jPanelInsertAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtEstante, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelInsertAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(txtPrateleira, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelInsertAcervoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanelInsertAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInsertAcervoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelInsertAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(45, 45, 45)
                        .addGroup(jPanelInsertAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(47, 47, 47))
                    .addGroup(jPanelInsertAcervoLayout.createSequentialGroup()
                        .addGroup(jPanelInsertAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addContainerGap())))
        );
        jPanelInsertAcervoLayout.setVerticalGroup(
            jPanelInsertAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInsertAcervoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInsertAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInsertAcervoLayout.createSequentialGroup()
                        .addGroup(jPanelInsertAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelInsertAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelInsertAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)))
                    .addGroup(jPanelInsertAcervoLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelInsertAcervoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEstante, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrateleira, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnExcluir.setText("Excluir");
        btnExcluir.setMaximumSize(new java.awt.Dimension(140, 25));
        btnExcluir.setMinimumSize(new java.awt.Dimension(140, 25));
        btnExcluir.setPreferredSize(new java.awt.Dimension(140, 25));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar");
        btnAtualizar.setMaximumSize(new java.awt.Dimension(140, 25));
        btnAtualizar.setMinimumSize(new java.awt.Dimension(140, 25));
        btnAtualizar.setPreferredSize(new java.awt.Dimension(140, 25));
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setMaximumSize(new java.awt.Dimension(140, 25));
        btnCadastrar.setMinimumSize(new java.awt.Dimension(140, 25));
        btnCadastrar.setPreferredSize(new java.awt.Dimension(140, 25));
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Campo de Pesquisa");

        btnListAllBooks.setText("Listar Todos os Livros");
        btnListAllBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListAllBooksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPesquisaLayout = new javax.swing.GroupLayout(jPanelPesquisa);
        jPanelPesquisa.setLayout(jPanelPesquisaLayout);
        jPanelPesquisaLayout.setHorizontalGroup(
            jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesquisaLayout.createSequentialGroup()
                .addGroup(jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPesquisaLayout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jLabel8))
                    .addGroup(jPanelPesquisaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnListAllBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelPesquisaLayout.createSequentialGroup()
                                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanelPesquisaLayout.setVerticalGroup(
            jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnListAllBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jLabel8))
        );

        txtBusca.setMaximumSize(new java.awt.Dimension(30, 100));
        txtBusca.setMinimumSize(new java.awt.Dimension(30, 100));
        txtBusca.setPreferredSize(new java.awt.Dimension(550, 700));

        btnBusca.setText("Pesquisar");
        btnBusca.setMaximumSize(new java.awt.Dimension(140, 25));
        btnBusca.setMinimumSize(new java.awt.Dimension(140, 25));
        btnBusca.setPreferredSize(new java.awt.Dimension(140, 25));
        btnBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelInsertAcervo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelInsertAcervo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jPanel1);
        jPanel1.getAccessibleContext().setAccessibleName("");
        jPanel1.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        Acervo ac = new Acervo();
        AcervoDAO dao = new AcervoDAO();
        
        ac.setTitulo(txtTitulo.getText());
        ac.setAno(Integer.parseInt(txtAno.getText()));
        ac.setEstante(Integer.parseInt(txtEstante.getText()));
        ac.setPrateleira(Integer.parseInt(txtPrateleira.getText()));
        ac.setStatus(Integer.parseInt(txtStatus.getText()));
        ac.setEditora(txtEditora.getText());
        
        dao.create(ac);
        cleanFields();
    }//GEN-LAST:event_btnCadastrarActionPerformed
    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
            Acervo ac = new Acervo();
            AcervoDAO dao = new AcervoDAO();
        if (tabelaAcervo.getSelectedRow() != -1){
            ac.setId((int)tabelaAcervo.getValueAt(tabelaAcervo.getSelectedRow(),0));
            ac.setAno((int)tabelaAcervo.getValueAt(tabelaAcervo.getSelectedRow(), 3));
            dao.delete(ac);
            readTabela();
            //cleanFields();
        }else{
            JOptionPane.showMessageDialog(null, "Selecione Um Livro para Excluir ");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
            Acervo ac = new Acervo();
            AcervoDAO dao = new AcervoDAO();
        if (tabelaAcervo.getSelectedRow() != -1){
            ac.setTitulo(txtTitulo.getText());
            ac.setEditora(txtEditora.getText());
            ac.setAno(Integer.parseInt(txtAno.getText()));
            ac.setStatus(Integer.parseInt(txtStatus.getText()));
            ac.setEstante(Integer.parseInt(txtEstante.getText()));
            ac.setPrateleira(Integer.parseInt(txtPrateleira.getText()));
            ac.setId((int)tabelaAcervo.getValueAt(tabelaAcervo.getSelectedRow(),0));
            dao.update(ac);
            cleanFields();
            
        }else{
            JOptionPane.showMessageDialog(null, "Selecione Um Livro para Editar ");
            
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void tabelaAcervoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaAcervoKeyReleased
        if (tabelaAcervo.getSelectedRow() != -1){                                        //EDITAR ITENS DA TABELA
            txtTitulo.setText(tabelaAcervo.getValueAt(tabelaAcervo.getSelectedRow(), 1).toString());
            txtEditora.setText(tabelaAcervo.getValueAt(tabelaAcervo.getSelectedRow(), 2).toString());
            txtAno.setText(tabelaAcervo.getValueAt(tabelaAcervo.getSelectedRow(), 3).toString());
            txtEstante.setText(tabelaAcervo.getValueAt(tabelaAcervo.getSelectedRow(), 4).toString());
            txtPrateleira.setText(tabelaAcervo.getValueAt(tabelaAcervo.getSelectedRow(), 5).toString());
            txtStatus.setText(tabelaAcervo.getValueAt(tabelaAcervo.getSelectedRow(), 6).toString());
        }else{
            JOptionPane.showMessageDialog(null, "Selecione Um Livro para Editar ");
        }

    }//GEN-LAST:event_tabelaAcervoKeyReleased

    private void tabelaAcervoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaAcervoMouseClicked

        if (tabelaAcervo.getSelectedRow() != -1){
            txtTitulo.setText(tabelaAcervo.getValueAt(tabelaAcervo.getSelectedRow(), 1).toString());
            txtEditora.setText(tabelaAcervo.getValueAt(tabelaAcervo.getSelectedRow(), 2).toString());
            txtAno.setText(tabelaAcervo.getValueAt(tabelaAcervo.getSelectedRow(), 3).toString());
            txtEstante.setText(tabelaAcervo.getValueAt(tabelaAcervo.getSelectedRow(), 4).toString());
            txtPrateleira.setText(tabelaAcervo.getValueAt(tabelaAcervo.getSelectedRow(), 5).toString());
            txtStatus.setText(tabelaAcervo.getValueAt(tabelaAcervo.getSelectedRow(), 6).toString());
        }else{
            JOptionPane.showMessageDialog(null, "Selecione Um Livro para Excluir ");
        }
    }//GEN-LAST:event_tabelaAcervoMouseClicked

    private void btnBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaActionPerformed
        Acervo ac = new Acervo();
        AcervoDAO db = new AcervoDAO();
        ac.setTitulo(txtBusca.getText());
        db.selectAcervo(ac.getTitulo());
        
    }//GEN-LAST:event_btnBuscaActionPerformed

    private void btnListAllBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListAllBooksActionPerformed
        readTabela();
//        DataBase db = new DataBase();
//        db.selectT_Acervo();
    }//GEN-LAST:event_btnListAllBooksActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnBusca;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnListAllBooks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelInsertAcervo;
    private javax.swing.JPanel jPanelPesquisa;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabelaAcervo;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtBusca;
    private javax.swing.JTextField txtEditora;
    private javax.swing.JTextField txtEstante;
    private javax.swing.JTextField txtPrateleira;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
